### ISSUE TITLE
NullPointerException: classBodyStream must not be null in Spring Boot packaged Jars

### ISSUE THREAD

**Issue by napstr** [Anamorphosee/stacktrace-decoroutinator#21]
I'm seeing an exception when trying to use this neat lib in Jars packaged by Spring Boot's Gradle Plugin.

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:95)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: java.lang.NullPointerException: classBodyStream must not be null
	at dev.reformator.stacktracedecoroutinator.jvmagentcommon.Utils_jvm_agent_commonKt.addDecoroutinatorClassFileTransformers(utils-jvm-agent-common.kt:46)
	at dev.reformator.stacktracedecoroutinator.runtime.DecoroutinatorRuntime.load(runtime-jvm.kt:26)
	at com.example.demo.DemoApplicationKt.main(DemoApplication.kt:11)
	... 8 more
```

Minimum steps to reproduce:
1. Go to https://start.spring.io/ and generate an all-Kotlin, Gradle project using no dependencies
![image](https://user-images.githubusercontent.com/6048348/216772260-0c0fef70-26a6-48bb-938f-cf735970d560.png)
2. Download it, add Decoroutinator
3. Build the jar with `./gradlew build` or `./gradlew bootJar`
4. Run it with `java -jar build/libs/demo-0.0.1-SNAPSHOT.jar`

You can find an example project here: https://github.com/napstr/stacktrace-decoroutinator-spring-boot-npe

Running the project from my IDE, or via `./gradlew bootRun` works fine.

Spring Boot does some classloader shenaningans when packaging the Jar, maybe that's the cause?

**Comment by Anamorphosee** [comment]
Thanks. Fixed at 2.3.6
