### ISSUE TITLE
Android: There are still some Fatal exception in coroutines machinery for CancellableContinuation

### ISSUE THREAD

**Issue by nordfalk** [Anamorphosee/stacktrace-decoroutinator#42]
After the fix in https://github.com/Anamorphosee/stacktrace-decoroutinator/issues/39 I could roll out to 4000 users and it works fine for almost all users.
However there are still crashes for a small fraction (5 users):

![image](https://github.com/user-attachments/assets/08885452-1116-4647-b39f-20a7b5b5cf6d)

Here are some stack traces:

```
kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for CancellableContinuation(DispatchedContinuation[AndroidUiDispatcher@e97cadc, Continuation at kotlinx.coroutines.JobSupport.joinSuspend(JobSupport.kt:1539)@1914962]){Completed}@89897e5. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
	at kotlinx.coroutines.C.e(DispatchedTask.kt:43)
	at kotlinx.coroutines.C.run(DispatchedTask.kt:213)
	at androidx.compose.ui.platform.AndroidUiDispatcher.m(AndroidUiDispatcher.android.kt:7)
	at androidx.compose.ui.platform.AndroidUiDispatcher.g(AndroidUiDispatcher.android.kt:1)
	at androidx.compose.ui.platform.AndroidUiDispatcher$c.run(AndroidUiDispatcher.android.kt:3)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.l0@1f5ad47, androidx.compose.runtime.BroadcastFrameClock@c509974, z{Active}@cade9d, AndroidUiDispatcher@e97cadc]
Caused by: java.lang.ExceptionInInitializerError
	at dev.reformator.stacktracedecoroutinator.common.internal.a.c(awakener.kt:68)
	at dev.reformator.stacktracedecoroutinator.common.internal.a.b(awakener.kt:80)
	at dev.reformator.stacktracedecoroutinator.common.internal.j.awakeBaseContinuation(provider-impl.kt:15)
	at g4.a.a(provider-api.kt:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:21)
	at kotlinx.coroutines.C.run(DispatchedTask.kt:129)
	... 11 more
Caused by: java.lang.NoSuchMethodException: dev.reformator.stacktracedecoroutinator.common.internal.v.unknown [interface dev.reformator.stacktracedecoroutinator.provider.DecoroutinatorSpec, class java.lang.Object]
	at java.lang.Class.getMethod(Class.java:2950)
	at java.lang.Class.getDeclaredMethod(Class.java:2929)
	at java.lang.invoke.MethodHandles$Lookup.findStatic(MethodHandles.java:842)
	at dev.reformator.stacktracedecoroutinator.common.internal.w.<clinit>(unknown.kt:20)
	... 17 more
```

```
kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for CancellableContinuation(DispatchedContinuation[AndroidUiDispatcher@9012039, Continuation at kotlinx.coroutines.JobSupport.joinSuspend(JobSupport.kt:1539)@8e032e7]){Completed}@262467e. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
	at kotlinx.coroutines.C.e(DispatchedTask.kt:43)
	at kotlinx.coroutines.C.run(DispatchedTask.kt:213)
	at androidx.compose.ui.platform.AndroidUiDispatcher.m(AndroidUiDispatcher.android.kt:7)
	at androidx.compose.ui.platform.AndroidUiDispatcher.g(AndroidUiDispatcher.android.kt:1)
	at androidx.compose.ui.platform.AndroidUiDispatcher$c.run(AndroidUiDispatcher.android.kt:3)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:9063)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.l0@ad84c8a, androidx.compose.runtime.BroadcastFrameClock@226d2fb, z{Active}@7f27f18, AndroidUiDispatcher@9012039]
Caused by: java.lang.ExceptionInInitializerError
	at dev.reformator.stacktracedecoroutinator.common.internal.a.c(awakener.kt:68)
	at dev.reformator.stacktracedecoroutinator.common.internal.a.b(awakener.kt:80)
	at dev.reformator.stacktracedecoroutinator.common.internal.j.awakeBaseContinuation(provider-impl.kt:15)
	at g4.a.a(provider-api.kt:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:21)
	at kotlinx.coroutines.C.run(DispatchedTask.kt:129)
	... 11 more
Caused by: java.lang.NoSuchMethodException: dev.reformator.stacktracedecoroutinator.common.internal.v.unknown [interface dev.reformator.stacktracedecoroutinator.provider.DecoroutinatorSpec, class java.lang.Object]
	at java.lang.Class.getMethod(Class.java:2950)
	at java.lang.Class.getDeclaredMethod(Class.java:2929)
	at java.lang.invoke.MethodHandles$Lookup.findStatic(MethodHandles.java:842)
	at dev.reformator.stacktracedecoroutinator.common.internal.w.<clinit>(unknown.kt:20)
	... 17 more
```

```
kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for CancellableContinuation(DispatchedContinuation[Dispatchers.Main.immediate, Continuation at kotlinx.coroutines.JobSupport.joinSuspend(JobSupport.kt:1539)@ecaf07b]){Completed}@e037c44. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
	at kotlinx.coroutines.C.e(DispatchedTask.kt:43)
	at kotlinx.coroutines.C.run(DispatchedTask.kt:213)
	at kotlinx.coroutines.K.processUnconfinedEvent(EventLoop.common.kt:16)
	at kotlinx.coroutines.internal.m.b(DispatchedContinuation.kt:147)
	at kotlinx.coroutines.internal.m.c(DispatchedContinuation.kt:6)
	at kotlinx.coroutines.internal.z.afterCompletion(Scopes.kt:15)
	at kotlinx.coroutines.JobSupport.continueCompleting(JobSupport.kt:18)
	at kotlinx.coroutines.JobSupport.access$continueCompleting(JobSupport.kt:1)
	at kotlinx.coroutines.JobSupport$b.o(JobSupport.kt:9)
	at kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:26)
	at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:80)
	at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:94)
	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:122)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:42)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:5)
	at kotlinx.coroutines.a.resumeWith(AbstractCoroutine.kt:7)
	at dev.reformator.stacktracedecoroutinator.common.internal.a.b(awakener.kt:154)
	at dev.reformator.stacktracedecoroutinator.common.internal.j.awakeBaseContinuation(provider-impl.kt:15)
	at g4.a.a(provider-api.kt:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:21)
	at kotlinx.coroutines.p0.afterResume(CoroutineContext.kt:60)
	at kotlinx.coroutines.a.resumeWith(AbstractCoroutine.kt:16)
	at dev.reformator.stacktracedecoroutinator.common.internal.a.b(awakener.kt:154)
	at dev.reformator.stacktracedecoroutinator.common.internal.j.awakeBaseContinuation(provider-impl.kt:15)
	at g4.a.a(provider-api.kt:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:21)
	at kotlinx.coroutines.C.run(DispatchedTask.kt:99)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:9063)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [z{Active}@de18b0, Dispatchers.Main.immediate]
Caused by: java.lang.ExceptionInInitializerError
	at dev.reformator.stacktracedecoroutinator.common.internal.a.c(awakener.kt:68)
	at dev.reformator.stacktracedecoroutinator.common.internal.a.b(awakener.kt:80)
	at dev.reformator.stacktracedecoroutinator.common.internal.j.awakeBaseContinuation(provider-impl.kt:15)
	at g4.a.a(provider-api.kt:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:21)
	at kotlinx.coroutines.C.run(DispatchedTask.kt:129)
	... 33 more
Caused by: java.lang.NoSuchMethodException: dev.reformator.stacktracedecoroutinator.common.internal.v.unknown [interface dev.reformator.stacktracedecoroutinator.provider.DecoroutinatorSpec, class java.lang.Object]
	at java.lang.Class.getMethod(Class.java:2950)
	at java.lang.Class.getDeclaredMethod(Class.java:2929)
	at java.lang.invoke.MethodHandles$Lookup.findStatic(MethodHandles.java:842)
	at dev.reformator.stacktracedecoroutinator.common.internal.w.<clinit>(unknown.kt:20)
	... 39 more
```

**Comment by Anamorphosee** [comment]
@nordfalk Seems this crashes are related to ProGuard minifier. Please add this ProGuard exclusions:
```
-keep class dev.reformator.stacktracedecoroutinator.common.internal.UnknownKt { *; }
```

**Comment by nordfalk** [comment]
One crash has emerged - during Google Play pre-test.
Should something more be added to ProGuard exclusions ?
If so, I'll do it right away, while not to many have recieved the update.


```
kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for CancellableContinuation(DispatchedContinuation[windowRecomposer cleanup.immediate, Continuation at kotlinx.coroutines.flow.StateFlowSlot.awaitPending(StateFlow.kt:430)@ce2b64]){Completed}@c62d40b. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
	at kotlinx.coroutines.C.e(DispatchedTask.kt:43)
	at kotlinx.coroutines.D.e(DispatchedTask.kt:40)
	at kotlinx.coroutines.D.a(DispatchedTask.kt:48)
	at kotlinx.coroutines.l.n(CancellableContinuationImpl.kt:8)
	at kotlinx.coroutines.l.C(CancellableContinuationImpl.kt:34)
	at kotlinx.coroutines.l.D(CancellableContinuationImpl.kt:8)
	at kotlinx.coroutines.l.resumeWith(CancellableContinuationImpl.kt:11)
	at kotlinx.coroutines.flow.StateFlowSlot.makePending(StateFlow.kt:58)
	at kotlinx.coroutines.flow.StateFlowImpl.updateState(StateFlow.kt:61)
	at kotlinx.coroutines.flow.StateFlowImpl.setValue(StateFlow.kt:6)
	at androidx.compose.runtime.Recomposer.i0(Recomposer.kt:143)
	at androidx.compose.runtime.Recomposer.v(Recomposer.kt:1)
	at androidx.compose.runtime.Recomposer$recompositionRunner$2$unregisterApplyObserver$1.a(Recomposer.kt:124)
	at androidx.compose.runtime.Recomposer$recompositionRunner$2$unregisterApplyObserver$1.invoke(Recomposer.kt:5)
	at androidx.compose.runtime.snapshots.SnapshotKt.A(Snapshot.kt:66)
	at androidx.compose.runtime.snapshots.SnapshotKt.B(Snapshot.kt:3)
	at androidx.compose.runtime.snapshots.SnapshotKt.b(Snapshot.kt:1)
	at androidx.compose.runtime.snapshots.GlobalSnapshot.o(Snapshot.kt:1)
	at androidx.compose.runtime.snapshots.A.o(Snapshot.kt:5)
	at androidx.compose.runtime.snapshots.A.o(Snapshot.kt:5)
	at androidx.compose.runtime.snapshots.A.o(Snapshot.kt:5)
	at androidx.compose.runtime.snapshots.A.o(Snapshot.kt:5)
	at androidx.compose.runtime.snapshots.h$a.e(Snapshot.kt:5)
	at androidx.compose.runtime.Recomposer.a(Recomposer.kt:88)
	at androidx.compose.runtime.ComposerImpl$b.a(Composer.kt:7)
	at androidx.compose.runtime.h.h(Composition.kt:9)
	at androidx.compose.runtime.h.setContent(Composition.kt:1)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.K(SubcomposeLayout.kt:15)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.I(SubcomposeLayout.kt:47)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.J(SubcomposeLayout.kt:59)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.H(SubcomposeLayout.kt:163)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$c.subcompose(SubcomposeLayout.kt:3)
	at androidx.compose.material3.ScaffoldKt$ScaffoldLayoutWithMeasureFix$1$1.a(Scaffold.kt:911)
	at androidx.compose.material3.ScaffoldKt$ScaffoldLayoutWithMeasureFix$1$1.invoke(Scaffold.kt:9)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$d.measure-3p2s80s(SubcomposeLayout.kt:113)
	at androidx.compose.ui.node.j.measure-BRTryo0(InnerNodeCoordinator.kt:56)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasureBlock$1.invoke(LayoutNodeLayoutDelegate.kt:2)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasureBlock$1.invoke(LayoutNodeLayoutDelegate.kt:1)
	at androidx.compose.runtime.snapshots.h$a.f(Snapshot.kt:65)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$a.i(SnapshotStateObserver.kt:46)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.o(SnapshotStateObserver.kt:103)
	at androidx.compose.ui.node.OwnerSnapshotObserver.i(OwnerSnapshotObserver.kt:3)
	at androidx.compose.ui.node.OwnerSnapshotObserver.g(OwnerSnapshotObserver.kt:17)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.R(LayoutNodeLayoutDelegate.kt:30)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.h(LayoutNodeLayoutDelegate.kt:1)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.K(LayoutNodeLayoutDelegate.kt:141)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.measure-BRTryo0(LayoutNodeLayoutDelegate.kt:60)
	at androidx.compose.foundation.layout.BoxMeasurePolicy.measure-3p2s80s(Box.kt:73)
	at androidx.compose.ui.node.j.measure-BRTryo0(InnerNodeCoordinator.kt:56)
	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(GraphicsLayerModifier.kt:1)
	at androidx.compose.ui.node.n.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:64)
	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(GraphicsLayerModifier.kt:1)
	at androidx.compose.ui.node.n.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:64)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasureBlock$1.invoke(LayoutNodeLayoutDelegate.kt:2)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasureBlock$1.invoke(LayoutNodeLayoutDelegate.kt:1)
	at androidx.compose.runtime.snapshots.h$a.f(Snapshot.kt:65)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$a.i(SnapshotStateObserver.kt:46)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.o(SnapshotStateObserver.kt:103)
	at androidx.compose.ui.node.OwnerSnapshotObserver.i(OwnerSnapshotObserver.kt:3)
	at androidx.compose.ui.node.OwnerSnapshotObserver.g(OwnerSnapshotObserver.kt:17)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.R(LayoutNodeLayoutDelegate.kt:30)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.h(LayoutNodeLayoutDelegate.kt:1)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.K(LayoutNodeLayoutDelegate.kt:141)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.measure-BRTryo0(LayoutNodeLayoutDelegate.kt:60)
	at androidx.compose.ui.layout.RootMeasurePolicy.measure-3p2s80s(RootMeasurePolicy.kt:41)
	at androidx.compose.ui.node.j.measure-BRTryo0(InnerNodeCoordinator.kt:56)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasureBlock$1.invoke(LayoutNodeLayoutDelegate.kt:2)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasureBlock$1.invoke(LayoutNodeLayoutDelegate.kt:1)
	at androidx.compose.runtime.snapshots.h$a.f(Snapshot.kt:65)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$a.i(SnapshotStateObserver.kt:46)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.o(SnapshotStateObserver.kt:103)
	at androidx.compose.ui.node.OwnerSnapshotObserver.i(OwnerSnapshotObserver.kt:3)
	at androidx.compose.ui.node.OwnerSnapshotObserver.g(OwnerSnapshotObserver.kt:17)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.R(LayoutNodeLayoutDelegate.kt:30)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.h(LayoutNodeLayoutDelegate.kt:1)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.K(LayoutNodeLayoutDelegate.kt:141)
	at androidx.compose.ui.node.LayoutNode.A0(LayoutNode.kt:20)
	at androidx.compose.ui.node.z.f(MeasureAndLayoutDelegate.kt:4)
	at androidx.compose.ui.node.z.z(MeasureAndLayoutDelegate.kt:18)
	at androidx.compose.ui.node.z.r(MeasureAndLayoutDelegate.kt:68)
	at androidx.compose.ui.platform.AndroidComposeView.onMeasure(AndroidComposeView.android.kt:105)
	at android.view.View.measure(View.java:26357)
	at androidx.compose.ui.platform.AbstractComposeView.internalOnMeasure$ui_release(ComposeView.android.kt:64)
	at androidx.compose.ui.platform.AbstractComposeView.onMeasure(ComposeView.android.kt:4)
	at android.view.View.measure(View.java:26357)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26357)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26357)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.D(CoordinatorLayout.java:1)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:311)
	at android.view.View.measure(View.java:26357)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:155)
	at android.view.View.measure(View.java:26357)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26357)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26357)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26357)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:760)
	at android.view.View.measure(View.java:26357)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3926)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2612)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2884)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2328)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9087)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:832)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [i0{Active}@45f23c7, windowRecomposer cleanup.immediate]
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at f4.f.d(specMethodsRegistry-generator-android.kt:7)
	at f4.f.b(specMethodsRegistry-generator-android.kt:1)
	at f4.b.f(specMethodsRegistry-generator-android.kt:26)
	at dev.reformator.stacktracedecoroutinator.common.internal.g.getSpecMethodFactoriesByStacktraceElement(specMethodsRegistry-common.kt:71)
	at dev.reformator.stacktracedecoroutinator.common.internal.a.c(awakener.kt:9)
	at dev.reformator.stacktracedecoroutinator.common.internal.a.b(awakener.kt:80)
	at dev.reformator.stacktracedecoroutinator.common.internal.j.awakeBaseContinuation(provider-impl.kt:15)
	at g4.a.a(provider-api.kt:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:21)
	at kotlinx.coroutines.D.d(DispatchedTask.kt:62)
	at kotlinx.coroutines.D.e(DispatchedTask.kt:25)
	... 132 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.compose.ui.platform.WindowRecomposerPolicy$createAndInstallWindowRecomposer$unsetJob$1" on path: DexPathList[[],nativeLibraryDirectories=[/system/lib64, /system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	... 144 more
	Suppressed: java.io.IOException: Bad range
		at dalvik.system.DexFile.openInMemoryDexFilesNative(Native Method)
		at dalvik.system.DexFile.openInMemoryDexFiles(DexFile.java:393)
		at dalvik.system.DexFile.<init>(DexFile.java:121)
		at dalvik.system.DexPathList.initByteBufferDexPath(DexPathList.java:264)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:226)
		at dalvik.system.InMemoryDexClassLoader.<init>(InMemoryDexClassLoader.java:40)
		at dalvik.system.InMemoryDexClassLoader.<init>(InMemoryDexClassLoader.java:52)
		at dalvik.system.InMemoryDexClassLoader.<init>(Native Method)
		at dalvik.system.InMemoryDexClassLoader.<init>(InMemoryDexClassLoader.java:63)
		at dalvik.system.InMemoryDexClassLoader.<init>(Native Method)
		at f4.f.c(specMethodsRegistry-generator-android.kt:112)
		at f4.f.a(specMethodsRegistry-generator-android.kt:1)
		at f4.b.f(specMethodsRegistry-generator-android.kt:22)
		... 140 more
```
